### ISSUE TITLE
the last printing of difference of chemical potential is wrong:

### ISSUE THREAD

**Issue by eeitan** [Green-Phys/green-mbpt#9]
**Describe the bug**
the last printing of difference of chemical potential is wrong:

Si_GW.o88295:       New chemical potential, μ =  2.722719311714172e-01
Si_GW.o88295:Chemical potential difference Δμ =  2.722719311714172e-01
Si_GW.o88312:       New chemical potential, μ =  2.722719311714172e-01
Si_GW.o88312:Chemical potential difference Δμ =  2.722719311714172e-01
Si_GW.o88312:       New chemical potential, μ =  2.722644209861755e-01
Si_GW.o88312:Chemical potential difference Δμ =  7.510185241699219e-06
Si_GW.o88312:       New chemical potential, μ =  2.722569108009338e-01
Si_GW.o88312:Chemical potential difference Δμ =  7.510185241699219e-06
Si_GW.o88312:       New chemical potential, μ =  2.722494006156921e-01
Si_GW.o88312:Chemical potential difference Δμ =  7.510185241699219e-06
Si_GW.o88312:       New chemical potential, μ =  2.722419202327728e-01
Si_GW.o88312:Chemical potential difference Δμ =  7.480382919311523e-06
Si_GW.o88312:    Event 'Chemical potential search' took         2.025448      0.194926      1.796626 s.
Si_GW.o88312:       New chemical potential, μ =  2.722344398498535e-01
Si_GW.o88312:Chemical potential difference Δμ =  2.722344398498535e-01

**Comment by iskakoff** [comment]
can not reproduce

**Comment by eeitan** [comment]
Is it about the band structure?
